---
image: node:alpine
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - ~/.npm
    - jest
stages:
  - test
  - deploy
before_script:
  - npm ci #load npm into pipeline image
# Commenting jest-tests out for now until we get that sorted
# @TODO Right now this setup assumes one set of tests for all branches. Since tests are stored in __tests__ on the branch itself, this setup should be sufficient, but additional research into pros and cons of this arch should be pursued.
#jest-tests:
  #stage: test
  #script:
    #- npx jest --ci

# @TODO: Adjust break out deployments (and test?) for specific branches (i.e. ->develop, ->demo, and ->master) by separate `npx expo publish` runs (expo has different --release-channels we can utilize for develop/demo/master, etc. See https://docs.expo.io/workflow/expo-cli/). See specific TODO markers below.

# Expo Deployments for non-prod (develop)
expo-deployments_develop:
  stage: deploy
  only:
    - develop
  script:
    - apk add --no-cache bash
    - npx expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD
    - npx expo publish --non-interactive #@TODO specific release channel for `deploy`

# Expo Deployments for non-prod (demo)
expo-deployments_demo:
  stage: deploy
  only:
    - demo
  script:
    - apk add --no-cache bash
    - npx expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD
    - npx expo publish --non-interactive #@TODO specific release channel for `demo`

# Expo Deployments for prod (master)
expo-deployments_master:
  stage: deploy
  only:
    - master
  script:
    - apk add --no-cache bash
    - npx expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD
    - npx expo publish --non-interactive #@TODO specific release channel for `master`
